### PR TITLE
Adding 187 Mathematics of Computer Graphics problems

### PR DESCRIPTION
**Pull request by nathancarter**
In Spring 2018 I taught a course on the math of computer graphics, using my MAA Press textbook "Introduction to the Mathematics of Computer Graphics."  As I did so, I created several WeBWorK problems for each chapter from 2 through 15 of the text and assigned them to my students, 187 problems in all.  I contribute them to the Open Problem Library here, if they seem good to you.

### CODE REVIEW

**Comment by jwj61** [comment]
I am going to merge this, but could I don't see a README file.  It should be at the top level of BentleyUniversity saying briefly what is here, and say who (by github id) is allowed to make additions or changes in the future.

**Comment by jwj61** [comment]
Also, all contributions go to Contrib.  I moved your directory there, so be sure to update (via git pull upstream master) to get your copy in sync with the OPL version of things.

**Comment by nathancarter** [comment]
Ok. Out of office at the moment. Will add README as soon as I can. Thanks for the fast turnaround!

**Comment by nathancarter** [comment]
OK I did this; it is PR #451.  Thanks!

**Pull request merged**
