### PR TITLE
Grammer mistake

### PR DESCRIPTION
**Pull request by joe-tom**
Forgot an article.

### CODE REVIEW

**Comment by jwj61** [comment]
I think the original is ok.  I am no grammer expert, and the phrasing seems to go well with the next phrase "square top of side ...", which also has no article.

**Comment by paultpearson** [comment]
According to one online grammar checker I used, "pyramid with a square base of side b = ..." is preferable to "pyramid with square base of side b = ..."  

I prefer "pyramid with a square base of side length b = ..."

**Comment by dlglin** [comment]
I’m with Paul.  When I first read it, I also thought "pyramid with a square base of side length b = …"

Danny
On Nov 28, 2016, at 9:43 AM, Paul Pearson <notifications@github.com<mailto:notifications@github.com>> wrote:


According to one online grammar checker I used, "pyramid with a square base of side b = ..." is preferable to "pyramid with square base of side b = ..."

I prefer "pyramid with a square base of side length b = ..."

**Comment by joe-tom** [comment]
Perfect, someone should merge it then.

**Pull request merged**
