### PR TITLE
Update Stewart5_7_4_2a.pg

### PR DESCRIPTION
**Pull request by Tanaquil18**
replaced select_multiple_checkbox with parserCheckboxList

### CODE REVIEW

**Comment by pstaabp** [comment]
This also looks like it needs to be perltidied.

**Comment by Tanaquil18** [comment]
I ran perltidy and committed again!

**Comment by pstaabp** [comment]
The two comments I mentioned earlier still need to be taken care of.

**Comment by Tanaquil18** [comment]
Which comments?  All I saw on this one was that it needed to be perltidied.  Is there something else I need to do?

**Comment by pstaabp** [comment]
Can you look at https://github.com/openwebwork/webwork-open-problem-library/pull/1069 ?

1) Line 23 should be removed
2) The SOLUTION should be switched to PGML_SOLUTION.

**Comment by Tanaquil18** [comment]
I still don't see where to find those 2 comments originally, but I see that last comment and I fixed them now!

**Review by drdrew42 — APPROVED** [review]

**Pull request merged**
