### PR TITLE
initial commit of RRCC problems for OpenStax algebra book

### PR DESCRIPTION
**Pull request by brendaforland**
Initial upload of the problems from RRCC and CCDenver.

### CODE REVIEW

**Comment by jwj61** [comment]
Please include a README file to specify whom should be contacted if there are questions about problems in the subdirectory.

**Comment by brendaforland** [comment]
Hi John,

Thanks for the email. I thought I did. Did it not save? I included the README file in the RRCC folder that indicated where the problems came from and to contact Brenda Forland at Brenda.Forland@rrcc.edu<mailto:Brenda.Forland@rrcc.edu> with questions.

Thanks,
Brenda Forland
Mathematics Department Chair
Mathematics Faculty
303-914-6443
[Description: cid:image002.jpg@01CD8F75.52632FB0]

**Comment by jwj61** [comment]
I didn't see the file at first.  I just modified it to contain your github login name since that is what I need to know who (what github id's) can modify files in this directory.

**Comment by brendaforland** [comment]
Okay. Thank you. I'll make sure to add my github login name in the future. Thank you so much for your help!

**Pull request merged**
