### PR TITLE
Contributions in game theory, cryptography, number theory, and even a little coding theory

### PR DESCRIPTION
**Pull request by johnperry-math**
I would like these problems considered for the OPL. They include problems in:

- combinatorial game theory: Nim, Chomp, Ideal Nim, Green Hackenbush (graphics included!), Red/Blue Hackenbush (graphics included!);
- cryptography: the classic ciphers substitution, Caesar, Vigenére, autokey, one-time pad, as well as the modern, asymmetric ciphers RSA and Elgamal, sometimes in multiple parts;
- number theory: problems I couldn't already find in the OPL, including Chinese Remainder Theorem, multiplicative inverses, Euler's φ-function and related theorems;
- some very simple coding theory (Luhn's algorithm and parity check).

In addition, some of the problems are very simple, because I was teaching a group of middle- and high-school students. Others are not simple at all.

### CODE REVIEW

**Comment by jwj61** [comment]
The current directory structure uses names of institutions at the top level (except for some legacy exceptions).  But, they don't include the contributor's name in the naming of directories.  Can you rename the directory to be like the others?  It should be possible with a single git mv command.

**Comment by johnperry-math** [comment]
I am traveling and will try to do it when I return on Monday. (tech issues) Do I delete this pull request and submit a new one, or will this one be fine?

**Comment by mgage** [comment]
If you change this branch on your github the change is automatically pushed to the pull request to openwebwork.
You don’t have to resubmit.

Take care,

mike

**Comment by johnperry-math** [comment]
This should now be done: I performed a `git mv ...`, `git add .`, `git commit -m '...'`, and `git push`. Let me know if it isn't showing up correctly for you, or if I should do more.

**Pull request merged**
