### PR TITLE
Create CHBE241

### PR DESCRIPTION
**Pull request by jverrett**
Creating a folder for uploading questions relating to chemical and biological engineering in CHBE 241: Material and Energy Balances. Questions uploaded will have been tested in at least one course iteration.

### CODE REVIEW

**Comment by jwj61** [comment]
For contrib folders, there is a list of people in the README file which are allowed to make changes to a given folder.  Can you have someone on that list add you to the list for UBC?

**Comment by jverrett** [comment]
Thanks John,

Will do.

Best,

Jonathan


--
Jonathan Verrett,  PhD, P.Eng.
Instructor
Faculty of Applied Sciences | Department of Chemical and Biological Engineering
The University of British Columbia | Vancouver Campus
427-2360 East Mall | Vancouver BC | V6T 1Z3 Canada
Phone 604 827 5685 l | Mobile 604 312 4762
jonathan.verrett@ubc.ca<mailto:jonathan.verrett@ubc.ca>

**Comment by jverrett** [comment]
Hi Warren,

Can you add me for editing access to the readme file on the UBC folder, should be here: https://github.com/openwebwork/webwork-open-problem-library/blob/master/Contrib/UBC/README.md

I got the below email from John Jones, who organizes the OPL, I had put in a contribution, but need to be on that list first.

Thanks,

Jonathan

**Comment by jverrett** [comment]
Hi Warren,

Realized I forgot to also include my github handle. It is “jverrett”

Thanks,

Jonathan

From: Verrett, Jonathan
Sent: August 7, 2019 12:29 PM
To: 'openwebwork/webwork-open-problem-library' <reply@reply.github.com>
Subject: RE: [openwebwork/webwork-open-problem-library] Create CHBE241 (#572)

Hi Warren,

Can you add me for editing access to the readme file on the UBC folder, should be here: https://github.com/openwebwork/webwork-open-problem-library/blob/master/Contrib/UBC/README.md

I got the below email from John Jones, who organizes the OPL, I had put in a contribution, but need to be on that list first.

Thanks,

Jonathan

**Pull request merged**
