### PR TITLE
Add new problems to the Utah library.

### PR DESCRIPTION
**Pull request by hphuang67**
Related to Intermediate Algebra.

### CODE REVIEW

**Comment by jwj61** [comment]
You should remove the .tgz files from the pull request and add a README file (as described in Contrib/README).

**Comment by hphuang67** [comment]
Thank you; I will redo.

**Comment by hphuang67** [comment]
Hi John, I believe I did what you asked. Please check again if the stuff in
Utah/Intermediate_Algebra is alright and available to the general public.

Thanks a lot. Ping

**Comment by hphuang67** [comment]
> You should remove the .tgz files from the pull request and add a README file (as described in Contrib/README).

Hi John, I believe I did what you asked. Please check again if the stuff in Utah/Intermediate_Algebra is alright and available to the general public. 

Thanks a lot. Ping

**Comment by jwj61** [comment]
Sorry to keep holding this up, but an essential part of the readme file is to give github names for the people who are allowed to make changes to this part of the repository.  It is how someone down the road knows whether or not to accept a pull request to make changes to these files.  It has to be at least one person, but can be a list of several.

**Comment by hphuang67** [comment]
> Sorry to keep holding this up, but an essential part of the readme file is to give github names for the people who are allowed to make changes to this part of the repository. It is how someone down the road knows whether or not to accept a pull request to make changes to these files. It has to be at least one person, but can be a list of several.

Hi John, the README now gives permission to all those twenty-eight persons in the OPL group. Is it good enough to merge, please? Thanks a lot for your update. 

Best, Ping

**Comment by hphuang67** [comment]
Hi John, the README now gives permission to all those twenty-eight persons
in the OPL group. Is it good enough to merge, please? Thanks a lot for your
update.

Best, Ping

**Comment by hphuang67** [comment]
If it is not clear enough, please tell me how you want it phrased or which
position in the repository you want me to put the file. This is my first
time; I am a simpleton and a pure newbie :)

Thanks a lot. Ping

**Pull request merged**
