### PR TITLE
Pcc production

### PR DESCRIPTION
**Pull request by Alex-Jordan**
This is mostly several months of bugfixes to problems in Contrib/PCC. 
Some edits to problem in the OPL itself made there way into the mix. I hope it's not too much of a pain to look them over. If you don't like the changes there, I can try to peel apart these things in git.

### CODE REVIEW

**Comment by jwj61** [comment]
There is a conflict, presumably from one of the two OPL problems you modified.  In general, you should "git pull --rebase upstream master" before the pull request.  Any conflicts will show up there, so all is well if it is clean, otherwise it tells you where the bad merge is and gives some instructions on what to do when the bad merge is fixed.

**Comment by Alex-Jordan** [comment]
All the conflicts are in files we haven't touched, so I'm not sure what's up. There was one in an authoring template from Fort Lewis, that looked identical to me in either version. The others are all in Linear Algebra problems from Rochester, where single quotes were removed from tagging information. I don't understand why this is a merge conflict instead of something git isn't handling naturally, but I'm going through each one to resolve. Should have an updated push soon.

**Comment by Alex-Jordan** [comment]
OK, after I did that and the `pull --rebase` finished, my status says
```
# Your branch and 'origin/master' have diverged,
# and have 289 and 558 different commits each, respectively.
```
I don't understand where all the divergence came from. I pulled `master`, and there appear to be hundreds of merge conflicts that all related to the tagging. I did `git reset --hard` to get back to the above status. Any idea why the retagging would be popping up as merge conflicts instead of just taking the new edits?

**Comment by jwj61** [comment]
Since github said it could not merge cleanly, the pull --rebase puts them in your version.  Once fixed, then yes, the version on your computer is out of sync with the github version so you would have to "git push --force" to put the current version on github.  I feel badly that I forgot to mention that.  If instead you pulled, that creates new conflicts.

I don't have time to look at the individual things now, but will (maybe next week).

**Comment by Alex-Jordan** [comment]
Oh, don't feel bad, everything is fine in its current state for now. This weekend I'll go back in and sort it out, including this branch for a pull request. Just having too many other pressing matters at the moment.

**Comment by jwj61** [comment]
I pushed these changes from my copy of the OPL, except for the files which are not PCC.  If you still want those changes, do them in a new pull request.

**Pull request closed without merging**
