### PR TITLE
Active Calculus def files

### PR DESCRIPTION
**Pull request by b-stone**
We added `def` files for the webwork problems of the 2018 updated HTML version of Active Calculus.

### CODE REVIEW

**Comment by jwj61** [comment]
You aren't listed in the README as someone who can make changes to this directory of Contrib.  The person listed there should have a pull request which adds you first if they want you to modify the contents of Westmont

**Comment by b-stone** [comment]
On line 12 of the README file I am listed as a contributor. Do we need to be more specific, i.e. give a list or something?

**Comment by b-stone** [comment]
Thanks. Should we redo our README file to make it less confusing? I can start it would a list of approved contributors if that would help.

**Comment by jwj61** [comment]
Yes, that would be helpful.

**Pull request merged**
