### PR TITLE
add discrete math questions for DMOI by Levin

### PR DESCRIPTION
**Pull request by oscarlevin**
I kindly request that the problems included here be considered for the OPL.  All problems should already be tagged, including levels and keywords.  Most of the problems here are substantially different from what is already available (and should vastly expand what is available in Discrete Mathematics).  

The problems align with my popular open source textbook [Discrete Mathematics: an Open Introduction](http://discrete.openmathbooks.org/dmoi3.html), and have been used by many instructors for at least two years, so should be mostly bug-free.

Thank you for your consideration.

### CODE REVIEW

**Comment by oscarlevin** [comment]
In an attempt to update my branch of the repo, I apparently pushed a lot of commits into this pull request.  Let me try to clean this up so it is just my new contributions.

**Comment by oscarlevin** [comment]
Fixed now, and new exercises for section 1.4 and 2.5 added (combinatorial proofs and induction)

**Comment by Alex-Jordan** [comment]
@drdrew42 Can you give me merge authority on this repo?

**Comment by oscarlevin** [comment]
It would be great to get this included in at least the Contrib directory, but preferably the official OPL.  Is there a step I've missed or some other action you need from me to complete this process?

**Comment by drdrew42** [comment]
I thought we'd discussed changes to taxonomy tagging -- but when I went back to review our email conversation, I found that I must have been thinking of someone else. We did discuss the taxonomy, but not any specifically requested changes -- which I was waiting to receive, mistakenly.

This PR will add your contributions to the `Contrib/` folder, and on our next OPL release, they'll be accessible in the Library Browser (by any WeBWorK course that is linked to `Contrib/` in their templates directory and has updated their OPL). As far as approval for OPL is concerned, we're hoping that the usage statistics collection effort (re-enabled as of WW-2.17 release) will give us better insight on Contrib/ content usage -- making it easier to approve content that is seeing more use 'in the wild,' so to speak. It may take some time as the usage data trickles in, but if you know of specific campuses/professors that are using your materials, you can do the following to speed things along:
1. Request they update their version of WeBWorK to 2.17
2. Request they update their version of the OPL and switch over to using your materials from `Contrib/` (rather than uploading your content into their local `templates/` directory). 
3. Request that they run `update-OPL` and submit their usage data at the end of each semester.

**Review by drdrew42 — APPROVED** [review]
Thanks for share all of this work with the community!

**Pull request merged**
