### PR TITLE
edits and additions to PCC problems

### PR DESCRIPTION
**Pull request by Alex-Jordan**
Unless I made a mistake, this giant commit is entirely contained within the PCC Contrib folder.

We manage our problems separately from the OPL. They are at this git repo: 
https://github.com/Alex-Jordan/PCC

There, these thousands of edits are committed atomically, slowly over time. But I can't think of a way to get all that commit metadata over to here. So it's just one massive commit.

### CODE REVIEW

**Comment by mgage** [comment]
Hi Alex, @Alex-Jordan 
A google search came up with this: at
https://stackoverflow.com/questions/17371150/moving-git-repository-content-to-another-repository-preserving-history



I think the commands you are looking for are:

cd repo2
git checkout master
git remote add r1remote **url-of-repo1**
git fetch r1remote
git merge r1remote/master --allow-unrelated-histories
git remote rm r1remote
After that repo2/master will contain everything from repo2/master and repo1/master, and will also have the history of both of them.

shareimprove this answer
edited Oct 29 '17 at 10:41


So I think it's possible to insert your problems into the main repos including history. 
I think you can do this all on your machine.  merging your local git repos into a clone
of the main  webwork-open-problem-library on your machine.  Then issuing a pull request to webwork-open-problem-library.  It's worth some experimenting.  If there are lots of potential conflicts with current copies of the PCC problems in Contrib I think there is a way to have the conflicts automatically resolved to take the new versions modified at PCC over the versions on the main repos. 

It's worth an experiment.

I've been working on a procedure for schools to follow to maintain a local version of 
the OPL in such a way that they can then upload the changes to the openwebwork OPL at the 
end of the semester.  You can see my preliminary version at https://demo.webwork.rochester.edu/moodle/mod/page/view.php?id=662.   I didn't get a chance to explain that in the mini course.  

I did explain the way someone can submit one problem to the OPL at 
https://demo.webwork.rochester.edu/moodle/mod/page/view.php?id=661

You and I should get together and come up with a document(s) of best practice for maintaining a site OPL that can be easily uploaded to the main OPL via pull requests.

I'd also like to have someone revamp my method for uploading a single problem to the OPL so that it can be accomplished with a single button push from the PGproblemEditor page.

**Comment by Alex-Jordan** [comment]
OK, I'll try this sometime soon. Thanks Mike! And yes, we should chat about those last two things. Closing for now.

**Comment by jwj61** [comment]
@Alex-Jordan I was away for a day, which I did not respond sooner.  I could see that it was only affecting Contrib/PCC, so I would have merged it.

**Comment by Alex-Jordan** [comment]
Thanks @jwj61 . I am interested in pursuing getting our git history included in the OPL with something like what Mike found. I'll need a dedicated bit of time to untangle things locally. 

In general, when Contrib problems are updated, but those problems have already been curated, tagged, and added to the OPL, is there any process for the updates to make it to the OPL as well? If not, I'm wondering if that is something to think about with what Mike mentions in his penultimate paragraph.

**Comment by jwj61** [comment]
No, there is no process to connect the changes with the OPL.  Some people make pull requests to the OPL part in parallel with the other request.  If that were the case, then the pull request to the OPL should have only a few files changed.

**Pull request closed without merging**
