### PR TITLE
Update Sage Embeds

### PR DESCRIPTION
**Pull request by drjt**
Using threes to allow 3D graphs to render. Also, adding pretty_print to
remove error messages for older html usage.

### CODE REVIEW

**Comment by drjt** [comment]
Updating existing sage 3d graphing problems

**Comment by jwj61** [comment]
It looks like you are changing OPL tags in one of the files.  Unless the old tags were wrong, please fix

**Comment by drjt** [comment]
I'll check.  I thought I grabbed a library version to edit and did not
change any of the tags. Perhaps I got an old version on one of them.

JT

via a Galaxy S6 far far away.

**Comment by drjt** [comment]
Tag fixed on problem.

**Pull request merged**
